### ISSUE TITLE
Unable to generate Allure Report File

### ISSUE THREAD

**Issue by deepakjalda** [Ukrainis/SeleniumSpecflowAllureTest#3]
I have cloned your Project, Tests where getting executing successfully but I didn't Find the allure report

**Comment by Ukrainis** [comment]
Hello,
After you executed tests, allure-results folder should appear in your file system (for every person it has different location). Then you need to download allure command line tools and run a command: 'allure.bat "path to allure-results folder"'
After this allure report will be generated.

**Comment by deepakjalda** [comment]
Thank you for the quick response 
Allure reports folder is generated for me in my local machine
But the folder is empty 
Doesn’t contains any file in it

**Comment by Ukrainis** [comment]
Sorry, my mistake. Command should be:
allure generate "path to allure-results folder"

**Comment by deepakjalda** [comment]
Thank you for the help..
